[package]
name = "cargo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p_1 = { package = "cargo_rename_demo", version = "0.1.0" }
p_2 = { package = "cargo_rename_demo", version = "0.2.0" }