[package]
name = "cargo_rename_demo"
version = "0.2.0"
edition = "2018"
license = "MIT"
description="cargo test lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]